services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build: ./client
    container_name: frontend_c
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app # Mount local client dir
      - /app/node_modules # Avoid overwriting node_modules
    command: npm run dev

  backend:
    build: ./server
    container_name: backend_c
    restart: always
    ports:
      - "9000:9000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    command:
      [
        "./wait-for-it.sh",
        "db:5432",
        "--",
        "sh",
        "-c",
        "npm run seed && node server.js",
      ]
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 0000
      DB_NAME: postgres

volumes:
  postgres_data:
